### ISSUE TITLE
Snickers locator seems to be incorrect.

### ISSUE THREAD

**Issue by bchmura-af** [elliot710/af-testing#2]
Are you sure that the locator for the snickers: 
https://github.com/elliot710/af-testing/blob/ae0ac85e7ba8b2cb7a393ae0f400ea9db5cd3a4a/e2e_tests/tests/steps/homepage.spec.ts#L47
is correct?
![Screenshot 2024-07-08 143836](https://github.com/elliot710/af-testing/assets/135336098/66979d86-3c48-4188-a5ea-8a29072ca344)

**Comment by elliot710** [comment]
This is the locator for getting the price. Because I don't have access to the API, I had to parse it from the page, then convert to int

**Comment by elliot710** [comment]
Oh, I know what the problem is. Not all products are available in all countries and you are definitely getting others.

**Comment by bchmura-af** [comment]
Also, please consider the line:
https://github.com/elliot710/af-testing/blob/ae0ac85e7ba8b2cb7a393ae0f400ea9db5cd3a4a/e2e_tests/tests/steps/homepage.spec.ts#L46

**Comment by elliot710** [comment]
done
