### ISSUE TITLE
Possible race condition with the explicit waitForTimeout

### ISSUE THREAD

**Issue by bchmura-af** [elliot710/af-testing#3]
It seems that something in this code block is malfunctioning:
https://github.com/elliot710/af-testing/blob/ae0ac85e7ba8b2cb7a393ae0f400ea9db5cd3a4a/e2e_tests/tests/steps/homepage.spec.ts#L72-L82
With several re-runs the Skittles were not always present in the basket:
![Screenshot 2024-07-08 144842](https://github.com/elliot710/af-testing/assets/135336098/33588cef-0545-450e-a67b-8cdb0cf8c8bd)
![Screenshot 2024-07-08 144757](https://github.com/elliot710/af-testing/assets/135336098/27dfa39f-c61a-47a1-beb4-b923eebc1b8c)

**Comment by elliot710** [comment]
got rid of
